---
title: "Cronbach's Alpha"
format: html
author:
    - Melanie Viola Partsch
    - Katharina Groskurth
    - Matthias Blümke
    - Isabelle Schmidt
keywords:
  - Survey Data
  - Measurement
  - Validity
license: "CC BY-NC 4.0"
citation: 
    type: "document"
    title: |
        R Code for the Development and Validation of Measurement Instruments in the Social Sciences: Psychometric Analyses (Dimensionality, Reliability, Measurement Invariance)
    container-title: GESIS, Cologne. Data File Version 1.0.0, 
    author:
      - Melanie Viola Partsch
      - Katharina Groskurth
      - Matthias Blümke
      - Isabelle Schmidt
    doi: 10.7802/1.1982
    issued: 2020
---

Load the required packages
```{r}
#| label: setup
library(rio)
library(dplyr)
library(psych)

packageVersion("rio")
packageVersion("dplyr")
packageVersion("psych")
```

Read the example data.

```{r}
#| label: read_data
example1 <- rio::import("example1.sav")
```

Compute Cronbach's alpha
```{r}
alpha <- psych::alpha(select(example1, bfi2_1, bfi2_16R, bfi2_31R, bfi2_46),
    n.iter = 1000
)

alpha # print standard output
round(alpha[["total"]][["raw_alpha"]], digits = 3) # print alpha value
round(alpha[["boot.ci"]], digits = 3) # print bootstrapped confidence intervals
```